#!/usr/bin/env python

"""
Command line interface to run directed acyclic graphs of data transformations.

bbt show

"""

from lib.parser import parse_meta
from pathlib import Path

path = Path('models')
if not path.exists():
    print("models directory not found.")
    exit(1)

paths = list(path.glob('**/*.sql'))

for path in paths:
    print(path)
    parse_meta(path.read_text())

